### ISSUE TITLE
Make the error message you get when bpfman times out more helpful

### ISSUE THREAD

**Issue by anfredette** [bpfman/bpfman#1018]
If a user tries to run a bpfman cli command while another instance of bpfman has the database locked,  they get the following message.

```
$ bpfman list
thread 'main' panicked at bpfman/src/main.rs:59:40:
Unable to open root database: Timed out
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at /home/afredette/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spin-0.5.2/src/once.rs:128:29:
Once has panicked
```

**Comment by astoycos** [comment]
```
[INFO  bpfman] Database lock is already held, retrying after 2000 milliseconds
[INFO  bpfman] Database lock is already held, retrying after 2000 milliseconds
thread 'tokio-runtime-worker' panicked at bpfman/src/lib.rs:141:53:
Unable to open root database: DatabaseLockError
```

This is what it looks like now, I think it's good enough :) 

Additionally now that none of our processes hold the lock for an extended period of time this shouldn't be an issue anymore, I'm ready to close this if you are @anfredette

**Comment by ZhangShuaiyi** [comment]
```
[INFO  bpfman::utils] Has CAP_BPF: true
[INFO  bpfman::utils] Has CAP_SYS_ADMIN: true
[INFO  bpfman] Database lock is already held, retrying after 1000 milliseconds
[INFO  bpfman] Database lock is already held, retrying after 1000 milliseconds
[INFO  bpfman] Database lock is already held, retrying after 1000 milliseconds
[INFO  bpfman] Database lock is already held, retrying after 1000 milliseconds
[INFO  bpfman] Database lock is already held, retrying after 1000 milliseconds
[INFO  bpfman] Database lock is already held, retrying after 1000 milliseconds
[INFO  bpfman] Database lock is already held, retrying after 1000 milliseconds
[INFO  bpfman] Database lock is already held, retrying after 1000 milliseconds
[INFO  bpfman] Database lock is already held, retrying after 1000 milliseconds
thread 'main' panicked at /root/go/src/github.com/bpfman/bpfman/bpfman/src/lib.rs:486:14:
Unable to open root database: DatabaseLockError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrac
```
This is what it looks like in `481eee86`.  I think it can ouput the error message `Unable to open root database: DatabaseLockError` but no need to panic.
