### ISSUE TITLE
Fresh deployment of Bpfman fails on OpenShift cluster

### ISSUE THREAD

**Issue by Bart97** [bpfman/bpfman#1311]
Hello. I've deployed Bpfman 5.2 on my freshly built OpenShift cluster. I'm not able to deploy any XDP programs, because it seems like bpfman-operator roles are misconfigured by default. Bpfman-operator pod logs show the following error:
```
E1014 17:51:00.848829 1 reflector.go:150] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go:106: Failed to watch *v1.SecurityContextConstraints: failed to list *v1.SecurityContextConstraints: securitycontextconstraints.security.openshift.io is forbidden: User "system:serviceaccount:bpfman:bpfman-operator" cannot list resource "securitycontextconstraints" in API group "security.openshift.io" at the cluster scope
W1014 17:51:49.616790 1 reflector.go:547] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go:106: failed to list *v1.SecurityContextConstraints: securitycontextconstraints.security.openshift.io is forbidden: User "system:serviceaccount:bpfman:bpfman-operator" cannot list resource "securitycontextconstraints" in API group "security.openshift.io" at the cluster scope
```
The workaround for this issue is to add the missing rules to bpfman-operator-role:
```
  - verbs:
      - get
      - list
      - create
      - watch
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
```

Unfortunately this still doesn't resolve the problem. I see that bpfman-daemon is created, but it's unable to start:
```
Events:
  Type     Reason        Age                    From                  Message
  ----     ------        ----                   ----                  -------
  Warning  FailedCreate  4m18s (x17 over 7m2s)  daemonset-controller  Error creating: pods "bpfman-daemon-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{2000}: 2000 is not an allowed group, provider restricted-v2: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used, spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[5]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[6]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[7]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[8]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[9]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[10]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[11]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[12]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[13]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[14]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[15]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, provider restricted-v2: .initContainers[0].runAsUser: Invalid value: 0: must be in the ranges: [1000690000, 1000699999], provider restricted-v2: .initContainers[0].privileged: Invalid value: true: Privileged containers are not allowed, provider restricted-v2: .initContainers[0].capabilities.add: Invalid value: "CAP_BPF": capability may not be added, provider restricted-v2: .initContainers[0].capabilities.add: Invalid value: "CAP_NET_ADMIN": capability may not be added, provider restricted-v2: .initContainers[0].hostNetwork: Invalid value: true: Host network is not allowed to be used, provider restricted-v2: .containers[0].privileged: Invalid value: true: Privileged containers are not allowed, provider restricted-v2: .containers[0].hostNetwork: Invalid value: true: Host network is not allowed to be used, provider restricted-v2: .containers[1].privileged: Invalid value: true: Privileged containers are not allowed, provider restricted-v2: .containers[1].hostNetwork: Invalid value: true: Host network is not allowed to be used, provider restricted-v2: .containers[2].hostNetwork: Invalid value: true: Host network is not allowed to be used, provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "bpfman-restricted": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
```

Here's the error message in a slightly more readable format:

`Error creating: pods "bpfman-daemon-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{2000}: 2000 is not an allowed group, provider restricted-v2: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used, spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[5]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[6]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[7]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[8]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[9]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[10]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[11]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[12]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[13]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[14]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[15]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, provider restricted-v2: .initContainers[0].runAsUser: Invalid value: 0: must be in the ranges: [1000690000, 1000699999], provider restricted-v2: .initContainers[0].privileged: Invalid value: true: Privileged containers are not allowed, provider restricted-v2: .initContainers[0].capabilities.add: Invalid value: "CAP_BPF": capability may not be added, provider restricted-v2: .initContainers[0].capabilities.add: Invalid value: "CAP_NET_ADMIN": capability may not be added, provider restricted-v2: .initContainers[0].hostNetwork: Invalid value: true: Host network is not allowed to be used, provider restricted-v2: .containers[0].privileged: Invalid value: true: Privileged containers are not allowed, provider restricted-v2: .containers[0].hostNetwork: Invalid value: true: Host network is not allowed to be used, provider restricted-v2: .containers[1].privileged: Invalid value: true: Privileged containers are not allowed, provider restricted-v2: .containers[1].hostNetwork: Invalid value: true: Host network is not allowed to be used, provider restricted-v2: .containers[2].hostNetwork: Invalid value: true: Host network is not allowed to be used, provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "bpfman-restricted": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]`

I'm not sure how to proceed with this error.

**Comment by Bart97** [comment]
> Thanks for reporting this issue, @Bart97. Could you provide more details on how you deployed the operator? We are aware of a known issue with the v0.5.2 release in the [community-operators-prod repository](https://github.com/redhat-openshift-ecosystem/community-operators-prod), which might be causing the problem. I'll be releasing v0.5.3 soon to address this, but we want to ensure there are no other underlying issues.

I followed the guide at [https://bpfman.io/v0.5.2/quick-start/#deploy-released-container-images-on-kubernetes](https://bpfman.io/v0.5.2/quick-start/#deploy-released-container-images-on-kubernetes). I see that bpfman v0.5.3 is released now, so I will try again using this version.

**Comment by anfredette** [comment]
Well, this is embarrassing, but we have another issue with v0.5.3.  GitHub changed their "ubuntu-latest" runner that we use to build from 22.04 to 24.04 which introduced an incompatibility with our container base image.  We'll get a v0.5.4 out today.

**Comment by Bart97** [comment]
No problem. For now I've deployed v0.5.1 via the Operator Hub in OpenShift. I'm still having issues, but I'm getting much further than I previously did.

**Comment by anfredette** [comment]
We appreciate you giving bpfman a try.  Please keep us posted on any issues you hit and we'll try to work with you.  I'll let you know when we think the next release is ready.

**Comment by Billy99** [comment]
@Bart97 I have been playing with loading bpfman on OpenShift this morning.

When you say you are still having issues, this is what I am seeing. I loaded the Community version of the bpfman Operator v0.5.1. bpfman-operator is installed cleanly from the OperatorHub. However when I load a test eBPF program, the eBPF program doesn't load (side note: OpenShift requires the SELinux version to work):

```
$ cd bpfman/examples/
$ make deploy-xdp-selinux
:

$ kubectl get pods -n go-xdp-counter
NAME                      READY   STATUS              RESTARTS   AGE
go-xdp-counter-ds-8vrk7   0/1     ContainerCreating   0          25s
:

$ kubectl get xdpprograms
NAME                     BPFFUNCTIONNAME   NODESELECTOR   STATUS
go-xdp-counter-example   xdp_stats         {}             ReconcileError

$ kubectl get bpfprograms
NAME                              TYPE   STATUS            AGE
go-xdp-counter-example-128b537e   xdp    bpfmanNotLoaded   2m53s
:

$ kubectl logs -n bpfman bpfman-daemon-2jxv8 -c bpfman
:
[INFO  bpfman] Database lock is already held, retrying after 10000 milliseconds
thread 'tokio-runtime-worker' panicked at /usr/src/bpfman/bpfman/src/lib.rs:337:10:
failed to initialize image manager: Error spawning blocking task to build sigstore repo inside of tokio: Failed to parse timestamp metadata: missing field `length` at line 14 column 4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
A month or so back, sigstore calls started failing because one of their dependencies changed (see #1241). So we turned off sigstore for a window and then added a flag to allow it to be turned off manually. This has been fixed in v0.5.2.

Is this what you are currently seeing on v0.5.1?


I loaded v0.5.2 of the community Bpfman Operator and everything seems to work. When we said the v0.5.2 Bpfman Operator was broken, the Red Hat version (eBPF Manager Operator) has some wrong image labels built in and we can't modify it. So you can try v0.5.2 of the community Bpfman Operator or wait for v0.5.4 which "should" be out today or tomorrow.

When you originally wrote the issue, based on your follow-up comments, I assume you tried to install on OpenShift using the KIND instructions. OpenShift has tighter security and requires so additional packages installed. For v0.5.4, I am going to try to make that clearer in the docs and point to some OpenShift specific instructions. As is, the documentation for OpenShift are lacking. Sorry about that.

**Comment by Billy99** [comment]
Correction to above.
**Community Bpfman Operator**: The image labels in the community Bpfman Operator v0.5.2 are pointing to `latest` and not `v0.5.2`. There was an issue where `ubuntu:latest` changed from 22.04 to 24.04 and gave us a mismatch of glibc in the bpfman container image that caused issues for a few days where bpfman image wouldn't start. That was fixed yesterday, so `v0.5.2` of community Bpfman Operator is working again, but remember it is pointing to `latest`.

**Red Hat eBPF Manager Operator**: Is a Red Hat version that is fixed and pinned to bpfman pre v0.5.2. It has been verified to run on OpenShift and would be another option to try if needed.

**Comment by Billy99** [comment]
@Bart97 I apologize, but I have not used an internal OpenShift Registry before. The second error (`Cannot fetch manifest of image-registry.openshift-image-registry...`) appears to be either bpfman can't fetch the image because of a permissions issue or it's not there. Assuming it's a permissions issue, I wonder if this might help. If you looks at [samples/bpfman.io_v1alpha1_xdp_pass_private_xdpprogram.yaml](https://github.com/bpfman/bpfman-operator/blob/main/config/samples/bpfman.io_v1alpha1_xdp_pass_private_xdpprogram.yaml#L18), there is an example of passing `imagepullsecret`. The [top](https://github.com/bpfman/bpfman-operator/blob/main/config/samples/bpfman.io_v1alpha1_xdp_pass_private_xdpprogram.yaml#L2) of the file shows a kubectl example of creating the secret. That might be what bpfman needs in order to access the internal OpenShift Registry. If not, send or link us the yaml used to load the XDP program so we can dig more into it.

**Comment by Bart97** [comment]
@Billy99 thank you again! That was it, I was missing the credentials. I'm getting yet another error, but I'd guess that this one is related to the program itself, so I'll try to work it out. The program is a simple "hello world" logged whenever a packet comes in, so hopefully it will be easy to debug.

```
{"level":"error","ts":"2024-10-18T06:59:34Z","msg":"Observed a panic","controller":"xdpprogram","controllerGroup":"bpfman.io","controllerKind":"XdpProgram","XdpProgram":{"name":"xdp-test"},"namespace":"","name":"xdp-test","reconcileID":"ba33db99-73d7-4ced-881f-1cd78bc0d136","panic":"runtime error: invalid memory address or nil pointer dereference","panicGoValue":"\"invalid memory address or nil pointer dereference\"","stacktrace":"goroutine 383 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x220c558, 0xc001888c00}, {0x1c26360, 0x3244500})\n\t/usr/src/bpfman-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:107 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:105 +0x112\npanic({0x1c26360?, 0x3244500?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x132\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).handleProgCreateOrUpdate(0xc000000900, {0x220c558, 0xc001888c00}, {0x221e590, 0xc000000900}, 0xc001889e00, 0xc000324700, 0xc001888ff0, 0x1, 0x0, ...)\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:796 +0x9f1\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileProgram(0xc000000900, {0x220c558, 0xc001888c00}, {0x221e590, 0xc000000900}, {0x2233f78?, 0xc0014a4388?}, 0xc001888ff0)\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:876 +0x5ad\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileCommon(0xc000000900, {0x220c558, 0xc001888c00}, {0x221e590, 0xc000000900}, {0xc000e8a720, 0x2, 0x0?})\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:167 +0x30b\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*XdpProgramReconciler).Reconcile(0xc000000900, {0x220c558, 0xc001888c00}, {{{0x0, 0x0}, {0xc0010f42c8, 0x8}}})\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/xdp-program.go:213 +0x592\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc001888b70?, {0x220c558?, 0xc001888c00?}, {{{0x0?, 0x0?}, {0xc0010f42c8?, 0x0?}}})\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:116 +0xd4\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x2224aa0, {0x220c590, 0xc000431360}, {{{0x0, 0x0}, {0xc0010f42c8, 0x8}}})\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:303 +0x3bc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x2224aa0, {0x220c590, 0xc000431360})\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263 +0x21d\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224 +0x8a\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 15\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:220 +0x490\n","stacktrace":"runtime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:881\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).handleProgCreateOrUpdate\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:796\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileProgram\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:876\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*ReconcilerCommon).reconcileCommon\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/common.go:167\ngithub.com/bpfman/bpfman-operator/controllers/bpfman-agent.(*XdpProgramReconciler).Reconcile\n\t/usr/src/bpfman-operator/controllers/bpfman-agent/xdp-program.go:213\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224"}
{"level":"error","ts":"2024-10-18T06:59:34Z","msg":"Reconciler error","controller":"xdpprogram","controllerGroup":"bpfman.io","controllerKind":"XdpProgram","XdpProgram":{"name":"xdp-test"},"namespace":"","name":"xdp-test","reconcileID":"ba33db99-73d7-4ced-881f-1cd78bc0d136","error":"panic: runtime error: invalid memory address or nil pointer dereference [recovered]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/usr/src/bpfman-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224"}
```

**Comment by Billy99** [comment]
This looks like a bpfman-agent panic, which shouldn't happen even if a given XDP program has issues. Can you send more logs? More bpfman-agent logs prior to the panic and maybe the bpfman logs to see if the program loaded or not?
```
kubectl logs -n bpfman bpfman-daemon-abcde -c bpfman-agent
kubectl logs -n bpfman bpfman-daemon-abcde -c bpfman
```
Thanks

**Comment by Bart97** [comment]
Hello @Billy99, here are the logs you requested. I've replaced all occurrences of my domain name in the logs with <MYDOMAIN>, as I'd rather not post the address of my test cluster publicly.

I have to note, that I was able to upload the example image provided in the tutorials and it worked.
I did also try building xdp_counter.c myself, but that fails.

[qbkml-bpfman-agent.log](https://github.com/user-attachments/files/17457239/qbkml-bpfman-agent.log)
[w5kkd-bpfman-agent.log](https://github.com/user-attachments/files/17457240/w5kkd-bpfman-agent.log)
[w99wc-bpfman.log](https://github.com/user-attachments/files/17457241/w99wc-bpfman.log)
[52wt7-bpfman-agent.log](https://github.com/user-attachments/files/17457242/52wt7-bpfman-agent.log)
[sx9h2-bpfman-agent.log](https://github.com/user-attachments/files/17457243/sx9h2-bpfman-agent.log)
[sx9h2-bpfman.log](https://github.com/user-attachments/files/17457245/sx9h2-bpfman.log)
[w99wc-bpfman-agent.log](https://github.com/user-attachments/files/17457246/w99wc-bpfman-agent.log)
[7gk88-bpfman.log](https://github.com/user-attachments/files/17457247/7gk88-bpfman.log)
[7gk88-bpfman-agent.log](https://github.com/user-attachments/files/17457248/7gk88-bpfman-agent.log)
[52wt7-bpfman.log](https://github.com/user-attachments/files/17457249/52wt7-bpfman.log)
[bm4g4-bpfman-agent.log](https://github.com/user-attachments/files/17457251/bm4g4-bpfman-agent.log)
[bm4g4-bpfman.log](https://github.com/user-attachments/files/17457252/bm4g4-bpfman.log)
[qbkml-bpfman.log](https://github.com/user-attachments/files/17457253/qbkml-bpfman.log)
[w5kkd-bpfman.log](https://github.com/user-attachments/files/17457254/w5kkd-bpfman.log)

**Comment by Billy99** [comment]
@Bart97 Sorry for the delay. I have been looking into your issue, but we also had some other bpfman fires that needed putting out. I can't fully reproduce your issue, but I see tracing through the logs a few items that need fixing on the error handling side. I wrote [bpfman-operator:Issue#328](https://github.com/bpfman/bpfman-operator/issues/328) (since operator is in a different repository) to track it. I'll let you know when I have it merged. Once again, sorry you having these issues.

**Comment by Billy99** [comment]
@Bart97 As an additional note, I think you said you wrote your own XDP program (similar to our example) but it might have issues? Trying to bubble up errors in K8s can be tricky sometimes. bpfman needs to be better, but we are sometimes limited by formatting it in yaml and dealing with multiple nodes, etc. I find it easier to get an eBPF program working first on a single host, then once I know it works, try to launch it in K8s. There are notes in the docs on how to run bpfman on a linux server, then use bpfman CLI to load and unload. Might be easier to debug you program that way. But just a suggestion.

**Comment by Bart97** [comment]
> @Bart97 As an additional note, I think you said you wrote your own XDP program (similar to our example) but it might have issues? Trying to bubble up errors in K8s can be tricky sometimes. bpfman needs to be better, but we are sometimes limited by formatting it in yaml and dealing with multiple nodes, etc. I find it easier to get an eBPF program working first on a single host, then once I know it works, try to launch it in K8s. There are notes in the docs on how to run bpfman on a linux server without K8s, then use bpfman CLI to load and unload. Might be easier to debug your program that way. But just a suggestion.

Thanks for for giving so much attention to this issue. I did try to write my own program, but I stopped that and started trying to just build one of the examples provided in the repository.

I can successfully deploy the example images provided in the tutorials. With those images the error I described doesn't happen.

When I build the same example myself then it will produce the error.
