### ISSUE TITLE
TracepointProgram fails with InvalidLink

### ISSUE THREAD

**Issue by npaton** [bpfman/bpfman#700]
I'm running bpfd from main (installed August 30th) in a OpenShift cluster (v4.12.6) and trying to create a Tracepoint program:

```yaml
apiVersion: bpfd.dev/v1alpha1
kind: TracepointProgram
metadata:
  labels:
    app.kubernetes.io/name: exec-init
  name: exec-init
  namespace: openshift-bpfd
spec:
  sectionname: sched_process_exec
  nodeselector: {}
  names:
  - sched/sched_process_exec
  bytecode:
    image:
      url: quay.io/hey/myprogram:latest
```

On the agents, it seem to load the bytecode, but then panics with an `InvalidLink` when trying to attach:

<details>
  <summary>Agent logs</summary>

```
[2023-09-11T07:41:18Z DEBUG bpfd::oci_utils::image_manager] bytecode is stored as tar+gzip file at /var/lib/bpfd/io.bpfd.image.content/quay.io/hey/myprogram-latest
[2023-09-11T07:41:18Z DEBUG bpfd::bpf] BpfManager::add_single_attach_program()
[2023-09-11T07:41:18Z DEBUG aya::bpf] BPF Feature Detection: Features {
        bpf_name: true,
        bpf_probe_read_kernel: true,
        bpf_perf_link: false,
        bpf_global_data: true,
        bpf_cookie: false,
        btf: Some(
            BtfFeatures {
                btf_func: true,
                btf_func_global: true,
                btf_datasec: true,
                btf_float: true,
                btf_decl_tag: false,
                btf_type_tag: false,
                btf_enum64: false,
            },
        ),
    }
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating map by symbol index Some(14), kind Maps at insn 38 in section 3
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating map by symbol index Some(14), kind Maps at insn 40 in section 5
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating map by symbol index Some(14), kind Maps at insn 51 in section 7
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating map by symbol index Some(14), kind Maps at insn 50 in section 9
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating program `sched_process_exit` function `sched_process_exit` size 48
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating call to callee address 0x0 in section 2 (relocation) at instruction 10
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee is `memset`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] linked function `memset` at instruction 48
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating program `sched_process_exit` function `memset` size 8
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] finished relocating program `sched_process_exit` function `memset`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee `memset` is at ins 48, 37 from current instruction 10
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating call to callee address 0x0 in section 2 (relocation) at instruction 25
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee is `memset`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee `memset` is at ins 48, 22 from current instruction 25
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] finished relocating program `sched_process_exit` function `sched_process_exit`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating program `sched_process_fork` function `sched_process_fork` size 58
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating call to callee address 0x0 in section 2 (relocation) at instruction 20
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee is `memset`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] linked function `memset` at instruction 58
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating program `sched_process_fork` function `memset` size 8
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] finished relocating program `sched_process_fork` function `memset`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee `memset` is at ins 58, 37 from current instruction 20
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating call to callee address 0x0 in section 2 (relocation) at instruction 35
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee is `memset`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee `memset` is at ins 58, 22 from current instruction 35
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] finished relocating program `sched_process_fork` function `sched_process_fork`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating program `LBB2_4` function `LBB2_4` size 0
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] finished relocating program `LBB2_4` function `LBB2_4`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating program `LBB3_2` function `LBB3_2` size 0
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] finished relocating program `LBB3_2` function `LBB3_2`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating program `sys_enter_arch_prctl` function `sys_enter_arch_prctl` size 57
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating call to callee address 0x0 in section 2 (relocation) at instruction 20
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee is `memset`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] linked function `memset` at instruction 57
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating program `sys_enter_arch_prctl` function `memset` size 8
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] finished relocating program `sys_enter_arch_prctl` function `memset`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee `memset` is at ins 57, 36 from current instruction 20
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating call to callee address 0x0 in section 2 (relocation) at instruction 34
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee is `memset`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee `memset` is at ins 57, 22 from current instruction 34
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] finished relocating program `sys_enter_arch_prctl` function `sys_enter_arch_prctl`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating program `LBB0_2` function `LBB0_2` size 0
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] finished relocating program `LBB0_2` function `LBB0_2`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating program `sched_process_exec` function `sched_process_exec` size 46
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating call to callee address 0x0 in section 2 (relocation) at instruction 10
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee is `memset`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] linked function `memset` at instruction 46
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating program `sched_process_exec` function `memset` size 8
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] finished relocating program `sched_process_exec` function `memset`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee `memset` is at ins 46, 35 from current instruction 10
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating call to callee address 0x0 in section 2 (relocation) at instruction 24
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee is `memset`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] callee `memset` is at ins 46, 21 from current instruction 24
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] finished relocating program `sched_process_exec` function `sched_process_exec`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating program `LBB2_2` function `LBB2_2` size 0
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] finished relocating program `LBB2_2` function `LBB2_2`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating program `LBB1_2` function `LBB1_2` size 0
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] finished relocating program `LBB1_2` function `LBB1_2`
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] relocating program `LBB3_5` function `LBB3_5` size 0
[2023-09-11T07:41:18Z DEBUG aya_obj::relocation] finished relocating program `LBB3_5` function `LBB3_5`
thread 'main' panicked at 'unable to get owned tracepoint attach link: InvalidLink', bpfd/src/bpf.rs:347:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-09-11T07:41:18Z WARN  bpfd::rpc] RPC load error: RecvError(
        (),
    )
[2023-09-11T07:41:18Z DEBUG trust_dns_proto::xfer::dns_exchange] io_stream is done, shutting down
```
</details>

I've been digging through the code, I haven't figured it out yet, maybe someone can help me find the way. Thanks!

**Comment by dave-tucker** [comment]
Thanks for the bug report.
The bug comes from the kernel version used in OpenShift 4.12 (4.18) which I do not think has support for using BPF_LINK_CREATE to attach tracepoint programs.
As such, we fail to pin the program to bpffs and panic.

There are 2 items to investigate here:

1. Whether the functionality has been backported or not and if there is a bug in detecting it
2. Whether we still manage the lifecycle of Tracepoint programs without pinning

**Comment by npaton** [comment]
Gotcha, thank you for the quick response! Looks bfp_link was added around kernel 5.7. OpenShift 4.13 is using kernel 5.14, so I imagine that's likely to have it. There are quite a few versions of OpenShift 4.12 above ours (which I imagine have RHEL/kernel updates), so there might be a chance it was back ported. Not sure how to find that out without testing different versions.

**Comment by josyulav** [comment]
Trying to run this on an standalone system while running bpfd
**RUST_LOG=debug cargo xtask integration-test -- test_load_unload_xdp test_proceed_on_xdp**

[DEBUG aya_obj::relocation] relocating call to callee address 0x1e0 in section 2 (relocation) at instruction 145
[DEBUG aya_obj::relocation] callee is `compat_test`
[DEBUG aya_obj::relocation] linked function `compat_test` at instruction 208
[DEBUG aya_obj::relocation] relocating program `xdp_dispatcher` function `compat_test` size 6
[DEBUG aya_obj::relocation] finished relocating program `xdp_dispatcher` function `compat_test`
[DEBUG aya_obj::relocation] callee `compat_test` is at ins 208, 62 from current instruction 145
[DEBUG aya_obj::relocation] finished relocating program `xdp_dispatcher` function `xdp_dispatcher`
[DEBUG bpfd::multiprog::xdp] XdpDispatcher::attach_extensions() for if_index 29, revision 1
[DEBUG aya_obj::btf::btf] [DATASEC] .rodata: fixup size to 51
[DEBUG aya_obj::btf::btf] [DATASEC] .rodata: VAR GLOBAL_u8: fixup offset 0
[DEBUG aya_obj::btf::btf] [DATASEC] .rodata: VAR GLOBAL_u32: fixup offset 4
[DEBUG aya_obj::btf::btf] [DATASEC] .rodata: VAR pass.____fmt: fixup not required
[DEBUG aya_obj::btf::btf] [DATASEC] license: fixup size to 13
[DEBUG aya_obj::btf::btf] [DATASEC] license: VAR _license: fixup offset 0
[DEBUG aya_obj::relocation] relocating map by section index 5, kind Rodata at insn 3 in section 3
[DEBUG aya_obj::relocation] relocating map by section index 5, kind Rodata at insn 6 in section 3
[DEBUG aya_obj::relocation] relocating map by section index 5, kind Rodata at insn 0 in section 3
[DEBUG aya_obj::relocation] relocating program `pass` function `pass` size 12
[DEBUG aya_obj::relocation] finished relocating program `pass` function `pass`
**[DEBUG bpfd::multiprog::xdp] XdpDispatcher::attach() for if_index 29, revision 1
thread 'main' panicked at bpfd/src/multiprog/xdp.rs:164:18:
called `Result::unwrap()` on an `Err` value: InvalidLink
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace**
[WARN  bpfd::rpc] RPC load error: RecvError(
        (),
    )
[DEBUG h2::codec::framed_write] send frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }
thread 'main' panicked at tests/integration-test/src/tests/utils.rs:182:43:
called `Result::unwrap()` on an `Err` value: OutputError { cmd: Some("\"/home/vjosyula/go/src/github.com/bpfd-dev/bpfd/target/debug/bpfctl\" \"load-from-image\" \"--global\" \"GLOBAL_u8=61\" \"GLOBAL_u32=0D0C0B0A\" \"--image-url\" \"quay.io/bpfd-bytecode/xdp_pass:latest\" \"--pull-policy\" \"Always\" \"xdp\" \"--iface\" \"veth-bpfd-host\" \"--priority\" \"242\" \"--proceed-on\" \"aborted\" \"drop\" \"pass\" \"tx\" \"redirect\" \"dispatcher_return\""), stdin: None, cause: Expected(Output { output: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "[DEBUG rustls::anchors] add_parsable_certificates processed 1 valid and 0 invalid certs\n[DEBUG hyper::client::connect::http] connecting to [::1]:50051\n[DEBUG hyper::client::connect::http] connected to [::1]:50051\n[DEBUG rustls::client::hs] No cached session for DnsName(\"localhost\")\n[DEBUG rustls::client::hs] Not resuming any session\n[DEBUG rustls::client::hs] Using ciphersuite TLS13_AES_256_GCM_SHA384\n[DEBUG rustls::client::tls13] Not resuming\n[DEBUG rustls::client::tls13] TLS1.3 encrypted extensions: [Protocols([ProtocolName(6832)]), ServerNameAck]\n[DEBUG rustls::client::hs] ALPN protocol is Some(b\"h2\")\n[DEBUG rustls::client::tls13] Got CertificateRequest CertificateRequestPayloadTLS13 { context: , extensions: [SignatureAlgorithms([ECDSA_NISTP384_SHA384, ECDSA_NISTP256_SHA256, ED25519, RSA_PSS_SHA512, RSA_PSS_SHA384, RSA_PSS_SHA256, RSA_PKCS1_SHA512, RSA_PKCS1_SHA384, RSA_PKCS1_SHA256]), AuthorityNames([DistinguishedName(30123110300e06035504030c07627066642d6361)])] }\n[DEBUG rustls::client::common] Attempting client auth\n[DEBUG h2::client] binding client connection\n[DEBUG h2::client] client connection bound\n[DEBUG h2::codec::framed_write] send frame=Settings { flags: (0x0), enable_push: 0, initial_window_si



[root@localhost bpfd]# cat /etc/redhat-release 
**Rocky Linux release 8.8 (Green Obsidian)**
[root@localhost bpfd]# uname -mrs
**Linux 4.18.0-477.27.1.rt7.290.el8_8.x86_64+debug x86_64**
[root@localhost bpfd]#

So does it mean, the kernel / os I am running bpfd is not supported.

**Comment by astoycos** [comment]
@josyulav That's a pretty old kernel, here https://bpfman.io/main/getting-started/building-bpfman/#kernel-versions are the versions we've verified standalone functionality on!

**Comment by npaton** [comment]
This can be considered resolved. Thank you!
